Design schemas reference, subject, action, acquisition and show ERD.
vathes/gao2018 pull request #1
Opened 2018-11-28 19:39 UTC by shenshan

2018-11-30 18:18 UTC, dimitri-yatsenko requested changes

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/action.py
> +    (injection_coordinate_ref) -> reference.CoordinateReference
Let's use the current renaming syntax:  
```
-> reference.CoordinateReference.proj(injection_coordinate_ref="coordinate_ref")
```

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/reference.py
> +    brain_location_name: varchar(64)
I suggest to just call this attribute `brain_location` for brevity.

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/reference.py
> +    brain_location_name: varchar(64)
Can we use a shorter datatype, e.g. `varchar(20)`?

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/acquisition.py
> +    (photo_stim_location) -> reference.BrainLocation
Please use the new notation for renaming attributes:
```
-> reference.BrainLocation.proj(photo_stim_location="brain_location")
-> reference.Hemisphere.proj(photo_stim_hemispher="hemisphere")
-> reference.CoordinateReference(photo_stim_coordinate_ref="coordinate_ref")
```

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/action.py
> +    definition = """
I think I would like to see the primary key here as 
```
-> subject.Subject
injection : smallint unsigned   # injection number for the subject
```
and include the other references among the secondary attributes.

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/behavior.py
> +    number_of_trials:
incomplete attribute definition

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/behavior.py
> +        trial_idx:
incomplete attribute definition

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/reference.py
> +    hemisphere_name: varchar(32)
Let's call the attribute `hemisphere` rather than `hemisphere_name` and make the datatype shorter, e.g. `varchar(8)`

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/reference.py
> +    animal_source_name: varchar(64)
Let's rename `animal_source_name` to `animal_source`, add a comment, and make the datatype shorter, e.g. `varchar(16)`.

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/reference.py
> +    probe_source_name: varchar(64)
Let's rename `probe_source_name` to `probe_source`, add a comment, and make the datatype shorter, e.g. `varchar(16)`.

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/reference.py
> +    virus_name: varchar(64) # name of the virus
Let's rename `virus_name` to `virus`, add a comment, and make the datatype shorter, e.g. varchar(20).

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/reference.py
> +    virus_lot_number=null:  varchar(128)  # lot numnber of the virus
Let's default to `""` rather than `null`

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/reference.py
> +    experimenter_name: varchar(64)
let's rename `experimenter_name` to `experimenter`

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/subject.py
> +    species_name: varchar(64)
let's rename `species_name` to `species`

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/subject.py
> +    allele_name: varchar(128)
let's rename `allele_name` to `allele`

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/subject.py
> +    strain_id: varchar(64)
let's rename `strain_id` to `strain`, add a comment, and make the datatype shorter, e.g. `varchar(24)`

2018-11-30 18:18 UTC, dimitri-yatsenko commented on pipeline/subject.py
> +    subject_id: varchar(64)  # name of the subject
let's renamed `subject_id` to `subject`

2018-12-03 17:04 UTC, shenshan commented on pipeline/behavior.py
> +    number_of_trials:
These are under development. I'll complete them later.

2018-12-03 17:06 UTC, shenshan commented on pipeline/behavior.py
> +        trial_idx:
These are under development. I'll complete them later.

2018-12-06 20:47 UTC, merged